[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flat_pca"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru==0.7.3",
    "numpy==2.5.3",
    "plotly==7.0.0",
    "polars==1.44.2",
    "scikit-learn==1.9.1",
]

[dependency-groups]
dev = [
    "wiggum",
    "ipykernel==7.3.0",
    "nbformat==5.11.1",
    "pylint==4.0.8",
    "pytest==9.1.1",
    "ruff==0.16.7",
]

[tool.hatch.version]
path = "VERSION"
pattern = '^(?P<version>\S+)\s*$'

[tool.hatch.build.targets.wheel]
packages = ["src/flat_pca"]

[tool.uv]
cache-dir = ".uv-cache"

[tool.uv.sources]
wiggum = { git = "https://github.com/ribuka/wiggum.git" }

[tool.pytest.ini_options]
norecursedirs = [".*", "tmp"]
